version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install yarn
      - yarn
  build:
    commands:
      - yarn build
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
